BLANK_IMPORTS = (r'^To be Assigned a Non-GA space$',)

INSTRUCTOR_NICKNAMES = {'Steve Constantine': 'Stephen Constantine',
	'Hossein Pishro Nik': 'Hossein Pishro-Nik',}

LOCATIONS = {
	'ECSC': {'title': 'Engineering Laboratory II',
		'imports': ((r'^Engineering & CmpSci II ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('59.220934', '-95.009765', 3)},
	'FAC':  {'title': 'Fine Arts Center',
		'imports': ((r'^Fine Arts Center ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Fine Arts Center Green room$', 'Green Room'),
			(r'^Fine Arts Center Bezanson Hall$', 'Bezanson Hall'),
			(r'^Fine Arts Center Scene Shop$', 'Scene Shop'),
			(r'^Fine Arts Center (?P<room>.*)$', '%(room)s'),),
		'map': ('-18.145851', '-35.947265', 3)},
	'THOM': {'title': 'Thompson Hall',
		'imports': ((r'^Thompson( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Thom0312 - Polisci room$', '312'),),
		'map': ('9.188870', '-82.089843', 3)},
	'PATT': {'title': 'Patterson Dorm',
		'imports': ((r'^Patterson Dormitory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-74.936566', '-67.763671', 3)},
	'WEBS': {'title': 'Webster Dorm',
		'imports': ((r'^Noah Webster House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('26.902476', '31.113281', 3)},
	'HERT': {'title': 'Herter Hall',
		'imports': ((r'^Herter( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Herter TV Studio$', 'TV Studio'),
			(r'^Herter (?P<room>\d+)$', '%(room)s'),),
		'map': ('-28.149503', '-53.525390', 3)},
	'OCAM': {'title': 'Off Campus',	
		'imports': ((r'^On-Line$', 'Online'),
			(r'^Off Campus room', ''),
			(r'^Off Campus Hadley$', 'Hadley'),
			(r'^Off Campus Amherst College$', 'Amherst College'),
			(r'^Off Campus Baystate Medical$', 'Baystate Medical'),
			(r'^Off Campus Holyoke Comm\. Col\.$', 'Mt. Holyoke CC'),
			(r'^Off Campus Smith$', 'Smith College'),
			(r'^Off Campus Hampshire Col\.$', 'Hampshire College'),)},
	'GRIN': {'title': 'Grinnell Arena',
		'imports': ((r'^Grinnell Arena$', ''),),
		'map': ('1.493971', '-94.482421', 3)},
	'GOES': {'title': 'Goessmann Lab',
		'imports': ((r'^Goessmann Laboratory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('47.635783', '-57.041015', 3)},
	'MRST': {'title': 'Marston Hall',
		'imports': ((r'^Marston( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('55.128649', '-74.53125', 3)},
	'SOM':  {'title': 'School of Management',
		'imports': ((r'^School of Manage?ment ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^ISOM G8$', 'G8'),),
		'map': ('-37.544577', '-27.465820', 3)},
	'MAH':  {'title': 'Mahar Auditorium',
		'imports': ((r'^Mahar ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-39.061849', '-21.005859', 3)},
	'GOOD': {'title': 'Goodell',
		'imports': ((r'^Goodell( Building)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-10.358151', '-74.443359', 3)},
	'BART': {'title': 'Bartlett Hall',
		'imports': ((r'^Bartlett Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-23.563987', '-68.071289', 3)},
	'MACH': {'title': 'Machmer Hall',
		'imports': ((r'^Machmer Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('15.199386', '-71.630859', 3)},
	'HASA': {'title': 'Hasbrouck Lab Addition',
		'imports': ((r'^Hasbrouck Lab Add(ition)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('34.885930', '-38.583984', 3)},
	'AGEB': {'title': 'Agricultural Engineering Building',
		'imports': ((r'^Ag\.? ?Engineering Bldg ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Ag\. Engin\. Bldg Annex (?P<annex>.*?) ro?o?m (?P<room>.*)$', '%(room)s (Annex %(annex)s)'))},
	'CLRK': {'title': 'Clark Hall',
		'imports': ((r'^Clark Hall ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Clark Hall$', '')),
		'map': ('-4.083452', '-15.600585', 3)},
	'HASB': {'title': 'Hasbrouck Lab',
		'imports': ((r'^Hasbrouck Laboratory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('27.499790', '-36.210937', 3)},
	'MUNS': {'title': 'Munson Hall',
		'imports': ((r'^Munson Hall Annex$', 'Annex'),),
		'map': ('-38.891032', '-57.656250', 3)},
	'LGRC': {'title': 'Lederle Graduate Research Center',
		'imports': ((r'^Lederle Grad Res\.? Ctr ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Lederle Lowrise (?P<room>.*)$', '%(room)s'),),
		'map': ('58.077876', '-50.537109', 3)},
	'COOL': {'title': 'Coolidge Dorm',
		'imports': ((r'^Coolidge House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-63.821287', '-82.617187', 3)},
	'ARTB': {'title': 'Art Barn',
		'imports': ((r'^Art Barn$', ''),)},
	'HAMP': {'title': 'Hampden DC',
		'imports': ((r'^Hampden Dining Commons ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-67.642676', '-80.683593', 3)},
	'LGRT': {'title': 'Lederle Graduate Research Tower',
		'imports': ((r'^Lederle Grad Res Tower ro?o?m ?(?P<room>.*)$', '%(room)s'),),
		'map': ('53.278353', '-57.216796', 3)},
	'GRAY': {'title': 'Grayson Dorm',
		'imports': ((r'^Grayson Dorm(itory)? ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Grayson$', ''),),
		'map': ('38.651198', '35.991210', 3)},
	'MOR4': {'title': 'Morrill Science Center IV',
		'imports': ((r'^Morril IV South ro?o?m (?P<room>.*)$', '%(room)s South'),
			(r'^Morrill Sci\. Ctr\. \(IV\) ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Morril Sci Center BldgIV (?P<room>.*)$', '%(room)s'),),
		'map': ('20.179723', '-26.630859', 3)},
	'STOC': {'title': 'Stockbridge Hall',
		'imports': ((r'^Stockbridge Hall ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Bowker Auditorium$', 'Bowker Auditorium'),),
		'map': ('37.579412', '-76.333007', 3)},
	'TOBN': {'title': 'Tobin Hall',
		'imports': ((r'^Tobin( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-26.588527', '-76.640625', 3)},
	'SART': {'title': 'Studio Arts Building',
		'imports': ((r'^Studio Arts Building ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-29.840643', '-4.965582', 3)},
	'BOWD': {'title': 'Bowditch Hall',
		'imports': ((r'^Bowditch Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('42.228517', '-102.612304', 3)},
	'CCTR': {'title': 'Campus Center',
		'imports': ((r'^Campus Center ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('31.578535', '-45.483398', 3)},
	'MOR3': {'title': 'Morrill Science Center III',
		'imports': ((r'^Morrill Sci\. Ctr\. \(III\) ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Morrill III ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-3.030812', '-21.708984', 3)},
	'FURC': {'title': 'Furcolo Hall',
		'imports': ((r'^Furcolo (Hall )?ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('76.465491', '-52.690429', 3)},
	'FERN': {'title': 'Fernald Hall',
		'imports': ((r'^Fernald Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-13.197164', '-1.362304', 3)},
	'DUDA': {'title': 'Duda Hall',
		'imports': ((r'^Duda ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('58.516651', '-85.253906', 3)},
	'ARND': {'title': 'Arnold Dorm',
		'imports': ((r'^Arndold Basement Conference 10$', 'Basement Conference 10'),
			(r'^Arnold House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('58.904645', '-40.341796', 3)},
	'MOR2': {'title': 'Morrill Science Center II',
		'imports': ((r'^Morrill Sci\. Ctr\. \(II\) ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('4.258768', '-23.291015', 3)},
	'PAIG': {'title': 'Paige Lab',
		'imports': ((r'^Paige Laboratory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('48.690960', '-80.156250', 3)},
	'CONT': {'title': 'Conte Polymer Research Center',
		'imports': ((r'^Conte Polymer Res Ctr ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Conte Polymer Res Ctr$', ''),),
		'map': ('57.680660', '-62.578125', 3)},
	'HILS': {'title': 'Hills House',
		'imports': ((r'^Hills( House)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-26.115985', '4.306640', 3)},
	'HILL': {'title': 'Hillel House',
		'imports': ((r'^Hillel House$', ''),),
		'map': ('-62.103882', '8.261718', 3)},
	'MULL': {'title': 'Mullins Center',
		'imports': ((r'^Mullins Center$', ''),),
		'map': ('2.372368', '-119.707031', 3)},
	'HRTA': {'title': 'Herter Hall Annex',
		'imports': ((r'^Herter Anx Dstnc Lrng Classrm$', 'Distance Learning Classroom'),)},
	'TOTM': {'title': 'Totman P.E. Building',
		'imports': ((r'^Totman Phys\. ?Ed\.? (Bldg\.|Building) ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Totman Phys\. Ed\. Bldg\. Gym$', 'Gym'),),
		'map': ('69.099939', '-38.144531', 3)},
	'HOLD': {'title': 'Holdsworth Hall',
		'imports': ((r'^Holdsworth Hall ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Holdsworth (?P<room>.*)$', '%(room)s')),
		'map': ('44.777935', '-91.318359', 3)},
	'GOEA': {'title': 'Goessmann Lab Addition',
		'imports': ((r'^Goessmann Lab\. Add(tn)? ro?o?m (?P<room>.*)$', '%(room)s'),)},
	'LIBR': {'title': 'W.E.B. DuBois Library',
		'imports': ((r'^Library Tower ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('4.959615', '-63.676757', 3)},
	'NEWA': {'title': 'New Africa House',
		'imports': ((r'^New Africa House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-8.841651', '17.182617', 3)},
	'RENC': {'title': 'Renaissance Center',
		'imports': ((r'^Renaissance Center N Pleasant$', ''),)},
	'WASH': {'title': 'Washington Dorm',
		'imports': ((r'^Washington Dormitory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-74.566736', '-76.816406', 3)},
	'MARC': {'title': 'Marcus Hall',
		'imports': ((r'^Marcus( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('54.007768', '-66.840820', 3)},
	'FLNT': {'title': 'Flint Lab',
		'imports': ((r'^Flint Lab(oratory)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('30.221101', '-78.002929', 3)},
	'DRAP': {'title': 'Draper Hall',
		'imports': ((r'^Draper Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('38.410558', '-64.951171', 3)},
	'LEWS': {'title': 'Lewis Dorm',
		'imports': ((r'^Lewis House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('62.267922', '-16.743164', 3)},
	'BUTT': {'title': 'Butterfield Dorm',
		'imports': ((r'^Butterfield House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-14.434680', '44.252929', 3)},
	'MOOR': {'title': 'Moore Dorm',
		'imports': ((r'^Moore House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-72.395705', '-92.592773', 3)},
	'GORM': {'title': 'Gorman Dorm',
		'imports': ((r'^Gorman House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-28.226970', '13.403320', 3)},
	'RAND': {'title': 'Rand Theater',
		'imports': ((r'^Rand Theater - Upper$', 'Upper'),)},
	'VANM': {'title': 'Van Meter Dorm',
		'imports': ((r'^Van Meter House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('3.864254', '42.539062', 3)},
	'JA':   {'title': 'John Adams Dorm',
		'imports': ((r'^John Adams Tower ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-73.503460', '-71.279296', 3)},
	'DSON': {'title': 'Dickinson Hall (Police Station)',
		'imports': ((r'^Dickinson( Hall)? ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Dickinson - Library$', 'Library'),),
		'map': ('-5.659718', '-86.791992', 3)},
	'BOYD': {'title': 'Boyden P.E. Building',
		'imports': ((r'^Boyden Phys\. Ed\. Bldg ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-39.368279', '-88.59375', 3)},
	'MOR1': {'title': 'Morrill Science Center I',
		'imports': ((r'^Morrill Sci\. Ctr\. \(I\) ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('20.303417', '-17.885742', 3)},
	'CHNA': {'title': 'Chenoweth Lab Addition',
		'imports': ((r'^Chenoweth Lab Addition ro?o?m (?P<room>.*)$', '%(room)s'),)},
	'SKIN': {'title': 'Skinner Hall',
		'imports': ((r'^Skinner( Hall| Building)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('30.259067', '-26.542968', 3)},
	'GUNN': {'title': 'Gunness Lab',
		'imports': ((r'^Gunness Laboratory$', ''),
			(r'^Gunness Lab(oratory)? ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('59.153403', '-77.607421', 3)},
	'DWIG': {'title': 'Dwight Dorm',
		'imports': ((r'^Dwight House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('64.642703', '-30.278320', 3)},
	'CHAB': {'title': 'Chabad House',
		'imports': ((r'^Chabad House$', ''),),
		'map': ('-62.895217', '-61.259765', 3)},
	'THAT': {'title': 'Thatcher Dorm',
		'imports': ((r'^Thatcher House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('58.355630', '-15.161132', 3)},
	'CHEN': {'title': 'Chenoweth Lab',
		'imports': ((r'^Chenoweth Lab ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Chenoweth Pilot Plant$', 'Pilot Plant'),),
		'map': ('34.452218', '-85.034179', 3)},
	'CS':   {'title':'Computer Science Building',
		'imports': ((r'^Computer Science (Bldg|Building) (?P<room>.*)$', '%(room)s'),),
		'map': ('62.875188', '-96.328125', 3)},
	'EMER': {'title': 'Emerson Dorm',
		'imports': ((r'^Emerson House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-64.848937', '-98.481445', 3)},
	'JQA':  {'title': 'John Quincy Adams Dorm',
		'imports': ((r'^John Quincy Adams Tower$', ''),),
		'map': ('-71.663662', '-74.707031', 3)},
	'KENN': {'title': 'Kennedy Dorm',
		'imports': ((r'^Kennedy House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-61.185624', '-79.277343', 3)},
	'ELAB': {'title': 'Engineering Lab',
		'imports': ((r'^Engineering Laboratory ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('60.586967', '-86.396484', 3)},
	'MARY': {'title': 'Mary Lyon Dorm',
		'imports': ((r'^Mary Lyon House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('56.752722', '-23.862304', 3)},
	'HICK': {'title': 'Curry Hicks P.E. Building',
		'imports': ((r'^Curry Hicks Phys\. Ed Bldg (?P<room>.*)$', '%(room)s'),),
		'map': ('-31.240985', '-65.258789', 3)},
	'EUGE': {'title': 'Eugene Field House',
		'imports': ((r'^Eugene Field House ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Eugene Field House$', ''),)},
	'FREN': {'title': 'French Hall',
		'imports': ((r'^French Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('7.449624', '-4.702148', 3)},
	'PIER': {'title': 'Pierpont Dorm',
		'imports': ((r'^Pierpont House ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Pierpont House$', ''),),
		'map': ('-75.275412', '-92.900390', 3)},
	'MELV': {'title': 'Melville Dorm',
		'imports': ((r'^Melville Hall ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('-56.607885', '-91.494140', 3)},
	'SCOL': {'title': 'South College',
		'imports': ((r'^South College ro?o?m (?P<room>.*)$', '%(room)s'),)},
	'DICK': {'title': 'Dickinson Dorm',
		'imports': ((r'^Emily Dickinson House ro?o?m (?P<room>.*)$', '%(room)s'),),
		'map': ('34.813803', '29.135742', 3)},
	'AEFS': {'title': 'Agricultural Engineering Farm Service Building',
		'imports': ((r'^Ag\.Engin Farm Srvc Bldg ro?o?m (?P<room>.*)$', '%(room)s'),)},
        'INTG': {'title': 'Integrated Sciences Building',
		'imports': ((r'^Integrated Sciences ro?o?m (?P<room>.*)$', '%(room)s'),
			(r'^Integrate?d Sciences (Bldg|Building|Lab) (?P<room>.*)$', '%(room)s'),
			(r'^Integrated Sci Bldg (?P<room>.*)$', '%(room)s'),),
		'map': ('37.439974', '-26.103515', 3)},
	'GORD': {'title': 'Gordon Hall',
		'imports': ((r'^Gordon Hall$', ''),),
		'map': ('-55.702355', '2.460937', 3)},
}
