INSTRUCTOR_NICKNAMES = {}

LOCATIONS = {'KRES': {'title': 'Kresge Centennial Hall'},
'TECH': {'title': 'Technological Institute'},
'PARK': {'title': 'Parkes Hall'},
'LUNT': {'title': 'Lunt Hall'},
'UNIV': {'title': 'University Hall'},
'ANN' : {'title': 'Annenberg Hall'},
'SWFT': {'title': 'Swift Hall'},
'REGE': {'title': 'Regenstein Hall of Music'},
'LIBR': {'title': 'University Library'},
'SEAR': {'title': 'Frances Searle Building'},
'CROW': {'title': 'McMillen Crowe Hall'},
'LOU' : {'title': 'Louis Hall'},
'FISK': {'title': 'Fisk Hall'},
'THIC': {'title': 'Theater Int Cntr'},
'LOCY': {'title': 'Locy Hall'},
'FEDC': {'title': 'Ford EDC'},
'MADM': {'title': 'Music Administration Bldg'},
'MTRB': {'title': 'McCormick Tribune'},
'PICK': {'title': 'Pick-Staiger'},
'LUTK': {'title': 'Lutkin Hall'},
'LEVR': {'title': 'Leverone Hall'},
'SCOT': {'title': 'Scott Hall'},
'CLRK': {'title': '555 Clark'},
'CHIC': {'title': '1815 Chicago'},
'MILL': {'title': 'Millar Chapel'},
'HINM': {'title': '1810 Hinman'},
'BLOC': {'title': 'Block Auditorium'},
'PANC': {'title': 'Pancoe'},
'DEAR': {'title': 'Dearborn Observatory'},
'AFAM': {'title': '620 Library Pl'},
'ISP' : {'title': 'ISP House'},
}

